[package]
name = "chal_one"
version = "0.1.0"
authors = ["pataidan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex="0.3.1"
base64="0.13.0"
lazy_static="1.4.0"